server:
  port: 8080
  servlet:
    context-path: /myBlog
spring:
  profiles:
    active: dev
admin:
  key: 406453373 # Long--作为admin的userId
  email: 406453373@qq.com # 管理员email-用于验证码登陆
  title: 寒浔的博客
  author: 寒浔