server:
  port: 8080
  servlet:
    context-path: /myBlog
spring:
  profiles:
    active: dev
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xmlJavaMailSender